src/BOReserva/Models/gestion_aviones/CAgregarAvion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BOReserva.Models.gestion_aviones
{
    public class CAgregarAvion
    {
        public String _matriculaAvion { get; set; }
        public String _modeloAvion { get; set; }
        public int _capacidadPasajerosTurista{ get; set; }
        public int _capacidadPasajerosEjecutiva { get; set; }
        public int _capacidadPasajerosVIP { get; set; }
        public int _capacidadMaximaCombustible { get; set; }
        public float _capacidadEquipaje { get; set; }
        public float _distanciaMaximaVuelo { get; set; }
        public float _velocidadMaximaDeVuelo { get; set; }
        
    }
}

src/BOReserva/Models/gestion_aviones/CGestion_avion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BOReserva.Models.gestion_aviones
{
    public class CGestion_avion
    {
        
        public String _matriculaConsultarEstadisticaAvion { get; set; }
        public float _kmsRecorridosConsultarEstadistica { get; set; }
        public float _combustibleConsumidoConsultarEstadistica { get; set; }
        public int _pasajerosTransportadosConsultarEstadistica { get; set; }
    }
}

src/BOReserva/Controllers/gestion_avionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOReserva.Models.gestion_aviones;
using System.Net;
using BOReserva.Servicio;

namespace BOReserva.Controllers
{
    public class gestion_avionesController : Controller
    {
        //
        // GET: /gestion_aviones/

        public ActionResult M02_GestionAviones()
        {
            CGestion_avion model = new CGestion_avion();
            return PartialView(model);
        }

        public ActionResult M02_AgregarAvion()
        {
            CAgregarAvion model = new CAgregarAvion();
            return PartialView(model);
        }


        [HttpPost]
        public JsonResult guardarAvion(CAgregarAvion model)
        {
            //Chequeo si los campos obligatorios estan vacios como medida de seguridad
            if ((model._matriculaAvion == null) || (model._modeloAvion == null) || (model._capacidadEquipaje == 0) || (model._capacidadMaximaCombustible == 0) || (model._distanciaMaximaVuelo == 0))
            {
                //Creo el codigo de error de respuesta (OJO: AGREGAR EL USING DE SYSTEM.NET)
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                //Agrego mi error
                String error = "Error, campo obligatorio vacio";
                //Retorno el error
                return Json(error);
            }
            //AGREGAR EL USING DEL MANEJADOR SQL ANTES (using BOReserva.Servicio; o using FOReserva.Servicio;)
            //instancio el manejador de sql
            manejadorSQL sql = new manejadorSQL();
            //realizo el insert
            bool resultado = sql.insertarAvion(model);
            //envio una respuesta dependiendo del resultado del insert
            if (resultado)
            { 
                return (Json(true, JsonRequestBehavior.AllowGet));
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                String error = "Error insertando en la BD";
                return Json(error);
            }
        }

        /*Metodo para consultar la matricula de un avion para sus estadisticas*/
        [HttpPost]
        public JsonResult consultarEstadisticasAvion(CGestion_avion model)
        {
            String prueba = model._matriculaConsultarEstadisticaAvion;
            return (Json(true, JsonRequestBehavior.AllowGet));
            
        }




    }
}

src/BOReserva/Views/gestion_aviones/M02_AgregarAvion.cshtml
@model BOReserva.Models.gestion_aviones.CAgregarAvion

<script src="~/Scripts/Scripts_Aviones/llamadas_generales.js"></script>

 

 <!---------------------- SECCION DE AGREGAR AVION ---------------->
@using (Html.BeginForm("guardarAvion", "gestion_aviones", null, FormMethod.Post, new { @id = "formGuardarAvion", @class = "form-horizontal" }))
{

<div class="row">
    <div class="col-md-12">
        <div class="box">
                 
            <div class="box-body">
                <h2 class="box-title"> Agregar Avión</h2>
                <div class="row">
                    <div class="col-md-12">

                        <div>
                            &nbsp;
                            <div class="col-md-12">
                                <div class="col-xs-6">
                                    <label for="matriculaAvion">Inserte la matrícula del Avión (<span style="color:red">*</span>):</label>
                                    @Html.TextBoxFor(m => m._matriculaAvion, null, new { @class = "form-control", @placeholder = "HK-4549", @id = "matriculaAvion" })

                                </div>
                                <div class="col-xs-6">
                                    <label for="capacidadPasajerosTurista">Capacidad de pasajeros (Clase Turista):</label>
                                    @Html.TextBoxFor(m => m._capacidadPasajerosTurista, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "capacidadTuristas", @min = 0 })
                                                                    
                                </div>
                            </div>
                        </div>

                        <div>
                            &nbsp;
                            <div class="col-md-12">
                                <div class="col-xs-6">
                                     <label for="modeloAvion">Inserte el modelo del Avión (<span style="color:red">*</span>):</label>
                                    @Html.TextBoxFor(m => m._modeloAvion, null, new { @class = "form-control", @placeholder = "Boeing 777", @id = "modeloAvion" })

                                </div>
                                <div class="col-xs-6">
                                   <label for="capacidadPasajerosVIP">Capacidad de pasajeros (Clase VIP):</label>
                                    @Html.TextBoxFor(m => m._capacidadPasajerosVIP, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "capacidadVIP", @min = 0 })

                                   
                                </div>
                            </div>
                            </div>

                        <div>
                            &nbsp;
                            <div class="col-md-12">
                                <div class="col-xs-6">
                                     <label for="capacidadEquipaje">Capacidad de Equipaje (En Kilos) (<span style="color:red">*</span>):</label>
                                    @Html.TextBoxFor(m => m._capacidadEquipaje, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "capacidadEquipaje", @min = 0 })

                                </div>
                                <div class="col-xs-6">
                                    <label for="capacidadPasajerosEjecutiva">Capacidad de pasajeros (Clase Ejecutiva):</label>
                                    @Html.TextBoxFor(m => m._capacidadPasajerosEjecutiva, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "capacidadEjecutiva", @min = 0 })

                                </div>
                            </div>
                        </div>

                        <div>
                            &nbsp;
                            <div class="col-md-12">

                                <div class="col-xs-6">
                                    <label for="capacidadCombustible">Capacidad de Combustible (En litros) (<span style="color:red">*</span>):</label>
                                    @Html.TextBoxFor(m => m._capacidadMaximaCombustible, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "capacidadCombustible", @min = 0 })

                                </div>

                                <div class="col-xs-6">
                                   <label for="velocidadMaximaDeVuelo">Velocidad Máxima de Vuelo (En Kilometros) :</label>
                                    @Html.TextBoxFor(m => m._velocidadMaximaDeVuelo, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "velocidadMaximaDeVuelo", @min = 0 })

                                </div>
                                <div class="col-xs-6">
                                   
                                </div>
                            </div>
                        </div>

                        <div>
                            &nbsp;
                            <div class="col-md-12">

                                <div class="col-xs-6">
                                    <label for="distanciaMaximaDeVuelo">Distancia Máxima de Vuelo (En Kilometros) (<span style="color:red">*</span>):</label>
                                    @Html.TextBoxFor(m => m._distanciaMaximaVuelo, null, new { @class = "form-control", @placeholder = "0", @type = "number", @id = "distanciaMaximaVuelo", @min = 0 })

                                </div>
                            </div>
                        </div>


                            <div class="col-md-12" style="margin-top:10px;">
                                <button type="button" id="aceptarAvion" class="btn btn-success" style="display:block; margin-left:auto; margin-right:auto;">Guardar</button>
                            </div>
                        </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
    
    @*<script>
    $("#aceptarAvion").click(function (e) {
        e.preventDefault();
        var form = $("#formGuardarAvion");
        $.ajax({
            url: "gestion_aviones/guardarAvion",
            data: form.serialize(),
            type: 'POST',
            success: function (data) {
                alert("Se guardo");
                $('#formGuardarAvion')[0].reset();
            }
        });
    });
</script>*@ 
}
<!------------------- FIN DE SECCION DE AGREGAR AVION ---------------->